[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
PORT = "3000" 