name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        
    - name: Build and run tests
      uses: docker/build-push-action@v4
      with:
        context: .
        target: test
        load: true
        tags: devops-api-test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Execute tests
      run: docker run --rm devops-api-test:latest
      env:
        CI: true
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      
  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract repository name to lowercase
      run: |
        echo "REPO_NAME=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        target: production
        tags: |
          ghcr.io/${{ env.REPO_NAME }}/devops_api:latest
          ghcr.io/${{ env.REPO_NAME }}/devops_api:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    # Notify about successful build
    - name: Notify about successful build
      run: |
        echo "Docker image has been built and pushed to GitHub Container Registry"
        echo "Railway will automatically deploy this version based on repository integration" 