name: Deploy to Railway

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
        env:
          CI: true
          MONGODB_URI: mongodb://localhost:27017/test
      
      - name: Deploy to Railway
        uses: railway/railway-github-action@v1
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: devops-api
          environment: production
          command: up 